### ISSUE TITLE
API für Ausgaben (Rechnungen)

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#109]
# Story

Als **Frontend-Entwickler** möchte ich eine **RESTful API** nutzen können, die mir die **Ausgaben für jeden Bommel** liefert, damit ich diese Daten in der Benutzeroberfläche anzeigen und weiterverarbeiten kann.

# Akzeptanzkriterien

- **REST-API mit ausschließlich Lesezugriff**: Die API soll nur Leseoperationen unterstützen, da das Erstellen von Daten in der Regel über BPMN-Prozesse erfolgt und direkt mittels Service Tasks abgewickelt wird. Ausnahme: Ein Bommel muss gesetzt werden können, `null` ist valide. 
- **Separater Quarkus-Service**: Es wird ein eigenständiger Quarkus-Service namens `app.hopps.fin` entwickelt, der **Kogito** für die Prozessautomatisierung integriert.
- **Datenpersistenz mit PostgreSQL und Panache**: Die Anwendung verwendet PostgreSQL als Datenbank und nutzt **Panache** für einen vereinfachten Datenzugriff.
- **Datenmodell nach Azure AI Service und/oder Zugferd Service**: Das Datenmodell orientiert sich an den Strukturen des Azure AI Service bzw. Zugferd Service, da diese Daten die Eingangsdaten sein werden, aus denen der `TransactionRecord` im Prozess generiert wird. 
- **Datenbankmigrationen mit Flyway**: **Flyway** wird eingesetzt, um Datenbankmigrationen zu verwalten und ein konsistentes Datenbankschema über verschiedene Umgebungen hinweg sicherzustellen.
- **Vertragsabsicherung mit Pact.io**: Die Integration und der Vertrag mit dem Organisations-Service werden mittels **Pact.io** getestet und abgesichert, um die Zuverlässigkeit zwischen den Services zu gewährleisten.

# Zusätzliche Details

- **Sicherheit**: Die API sollte sichere Endpunkte bereitstellen und Authentifizierung sowie Autorisierung berücksichtigen. Wir verwenden OpenFGA.
 - Es gibt einen Bommelwart pro Bommel, dieser Bommelwart darf editieren, löschen und anlegen an allen Bommeln transitiv unter ihm. 
 - Es gibt Mitarbeiter an einem Bommel, diese dürfen für alle Bommel transitiv unterhalb Rechnungen einreichen.  
- **Dokumentation**: Eine umfassende API-Dokumentation, idealerweise mit OpenAPI/Swagger, soll bereitgestellt werden, um die Integration für Frontend-Entwickler zu erleichtern.
- **Fehlerbehandlung**: Angemessene Fehlermeldungen und HTTP-Statuscodes sollen implementiert werden, um eine effiziente Fehlerbehandlung zu ermöglichen.
- **Performance**: Die API sollte performant sein und auch bei hoher Last zuverlässige Antwortzeiten bieten.
- **Testing**: Unit-Tests und Integrationstests sollen erstellt werden, um die Qualität und Stabilität des Services sicherzustellen. Der org Service wird mit Pact gemockt.

**Comment by d135-1r43** [comment]
Leicht verblockt von https://github.com/hopps-app/hopps/issues/80

**Comment by d135-1r43** [comment]
Wie ist hier der Stand?

**Comment by 3thr3n** [comment]
@d135-1r43 Ich bin jetzt so weit, dass ich den rest-client schreiben müsste. Habe bloß kein plan wie ich das machen soll, wenn es halt keine Infos from ZugPferD oder dem az-document service topic gibt.
Hier fehlen nicht nur die Informationen aus den jeweiligen services, es fehlt auch im org-service an den bestimmten Endpunkten (kleineres Problem).

**Comment by d135-1r43** [comment]
Lass uns den Blocker heute Abend im Weekly klären.
