### ISSUE TITLE
Zeiterfassungssystem

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#11]
# Story

Den Mitarbeitern steht ein pragmatisches und einfaches System zur Erfassung ihrer Arbeitszeit zur Verfügung.

# Akzeptanzkriterien

- Webapp, man kann die Zeit ohne Installation einer Software erfassen
- DSGVO konform
- Das Leitungsteam hat personenbezogenen Zugang zu dem System

**Comment by manuelhummler** [comment]
Ich habe bei Jakob und Quirin nachgefragt, welches Open Source Tool die beiden aktuell verwenden und werde das ganze evaluieren.

**Comment by manuelhummler** [comment]
Vorschlag wäre: https://titra.io

Ich fände es cool, wenn wir einen Keycloak aufsetzen, über den wir Identities anlegen UND unsere Azure Open Project Konten als ID Quelle mit einbinden. Den kann man dann in Titra gleich vernünftig verlinken.
https://wiki.titra.io/books/deployment/page/openid-connect-oidc-authentication

**Comment by manuelhummler** [comment]
Ich könnte mich darum kümmern, allerdings erst ab September.

**Comment by d135-1r43** [comment]
Dann machen wir ein Provisorium mit Google Docs. @sk2675 ist dran.

**Comment by sk2675** [comment]
Hier das Provisorium mit Google-Docs: 

Bei Verbesserungsvorschläge einfach ändern.

[https://docs.google.com/spreadsheets/d/1jf6f4UGU1N4jtBvJoBxJ1ZTuzux20zniBR_fwIJAsmc/edit?usp=sharing](url)

**Comment by d135-1r43** [comment]
Jo, macht den Job. Man muss halt die Formeln kopieren -- was aber okay ist. @manuelhummler muss sich damit halt wohlfühlen, da er die Auszahlungen machen wird.

**Comment by blackwolfk-9** [comment]
Habe mir mal ein paar Tools angeschaut. @manuelhummler wenn du erfahrung mit titra hast würde ich das empfehlen. Sonst wäre z.B. Kimai für mehr scalierbarkeit besser geeignet. Informationen findet ihr hier: https://openprojectpaf.sharepoint.com/:x:/s/hopps/ETWcQysqTlNJoOTdRSgU5oYBZM8gDukz6HtuZYpaIGLb4g?e=dMaB1e
Gerne können wir das kurz zusammen endscheiden und uns dann um das aufsetzten kümmern.
