### ISSUE TITLE
Spike für ID Service

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#12]
# User Story

Als Product Owner möchte ich eine fundierte Entscheidung darüber treffen können, welchen ID-Service wir primär unterstützen, um sicherzustellen, dass dieser unseren technischen und geschäftlichen Anforderungen entspricht.

#Akzeptanzkriterien

- **Vergleich der ID-Services**: Die ID-Services Keycloak, Logto und Stack Auth werden systematisch miteinander verglichen.
- **Lizenz- und Geschäftsmodellanalyse**: Die Art der Lizenz und das Geschäftsmodell jedes ID-Services werden detailliert analysiert. Ein Ausschlusskriterium ist die Nicht-Kompatibilität mit der MIT-Lizenz.
- **Analyse der APIs und SDKs**: Die Qualität der APIs und SDKs jedes ID-Services wird bewertet. Dabei liegt der Fokus insbesondere auf:
  - Verfügbarkeit und Reifegrad von SDKs für React.
  - Nutzbarkeit und Integration der APIs im Java Backend.

### Zusatzhinweise

- Die Ergebnisse sollten eine klare Empfehlung enthalten, welcher ID-Service primär unterstützt werden soll.
- Es sollte auch dokumentiert werden, warum bestimmte ID-Services aufgrund der Akzeptanzkriterien ausgeschlossen wurden.

**Comment by d135-1r43** [comment]
@schitcrafter, magst du das machen?

**Comment by schitcrafter** [comment]
Nein, tut mir leid. Zu wenig knowledge mit Geschäftsmodellen/Lizenzen, plus Auth ist ein Bereich in dem ich mich nicht gut auskenne

**Comment by d135-1r43** [comment]
Voll okay. Ich würde dann fast zum wont fix tendieren. Wir nehmen einfach Keycloak.

**Comment by d135-1r43** [comment]
Wie im Slack abgestimmt nehmen wir Keycloak ohne einen Spike zu machen.
