### ISSUE TITLE
Dependency Track Build verbessern

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#127]
1. **Matrix-Builds zur Optimierung**  
   Implementiere einen Matrix-Build, um redundante Blockkopien zu vermeiden und die Konfigurationseffizienz zu erhöhen. Dies reduziert die Wartung und vereinfacht zukünftige Erweiterungen.

2. **Version aus `pom.xml` und `package.json`**  
   Stelle sicher, dass die korrekte Version aus den Dateien `pom.xml` (für Java) und `package.json` (für JavaScript-Projekte) verwendet wird, anstatt standardmäßig statisch`main` zu nutzen. Dies gewährleistet eine genauere Versionsverwaltung und minimiert Konflikte bei der Abhängigkeitspflege. Zudem kann sichergestellt werden, dass aufgekommene Sicherheitslücken geschlossen wurden. 

3. **Integration der SPA und mobilen Apps mit SBOM-Unterstützung**  
   Füge die Single-Page-Anwendung (SPA) und die mobilen Apps in den Workflow ein und erzeuge SBOM-Daten (Software Bill of Materials) für eine bessere Nachverfolgbarkeit und Sicherheit. Hierbei kann die offizielle [npm-sbom-Dokumentation](https://docs.npmjs.com/cli/v10/commands/npm-sbom) als Referenz dienen.

**Comment by 3thr3n** [comment]
Kannst du Punkt 2 erklären? Punkt 2 ist für mich nicht klar genug, dass ich da was machen kann.

**Comment by 3thr3n** [comment]
Ah, ich sehe gerade was du vll meinst. Geht es um die projectVersion für die sBom aka DependencyTrack?

**Comment by 3thr3n** [comment]
Ich habe die dev-dependency von [cyclonedx](https://www.npmjs.com/package/@cyclonedx/cdxgen) genutzt, da pnpm dies nicht oob unterstützt. Dies ist in meinen Augen eine sinnvollere Lösung als auf npm zurück zu fallen.
