### ISSUE TITLE
Sonarqube für Backend

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#14]
# Story

Als Developer haben wir einen SonarQube, der fortlaufend die Qualität das Java Codes im Backend überwacht. 

# Akzeptanzkriterien

- Wir bevorzugen SaaS über self-hosted. Wenn self-hosted notwendig sein sollte, muss der PO freigeben. 
- Nach Möglichkeit nutzen wir kostenlose Angebote für Non-Profits und FOSS Software. Sollte es dennoch zu Kosten kommen, muss @manuelhummler diese freigeben. 
- Der SonarQube Build läuft möglichst oft und automatisch, mindestens gegen main, besser bei jedem PR.

**Comment by MatthiasRaimann** [comment]
Ich würde hierfür den "cloud-based" Service von Sonar Qube nehmen. Ist kostenlos für Open-Source Software.
<img width="387" alt="image" src="https://github.com/user-attachments/assets/f6a2db9e-710a-44d1-b1fd-e40fe96978b9">

**Comment by MatthiasRaimann** [comment]
@d135-1r43 du solltest eine Anfrage vorliegen haben, dass der SonarQube auf das Repo zugreifen darf.

**Comment by d135-1r43** [comment]
Ich habe es gerade angenommen und dann auch gleich den Wizzard durchgeklickt. https://sonarcloud.io/project/configuration?id=hopps-app_hopps

Kannst du mal schauen, ob alles passt?

**Comment by MatthiasRaimann** [comment]
![image](https://github.com/user-attachments/assets/d8c6255a-99ef-4391-8923-be908852768b)
Gerade ist alles was ich sehen kann das hier...
Brauche ich eine Berechtigung um hier weitere Einstellungen vornehmen zu können?

Ich kann auch keine Keys sehen, die ich brauche, um damit das Projekt in der Pipeline checken zu lassen.
<img width="1362" alt="image" src="https://github.com/user-attachments/assets/a916fe86-9a3a-4af3-a05a-eb9e6b07c93f">

**Comment by MatthiasRaimann** [comment]
Ich benötige Berechtigungen um im Repo Credentials eintragen zu können (SonarQube-Token)
@d135-1r43 , @schitcrafter @D4ykoo

**Comment by schitcrafter** [comment]
Per GitHub docs braucht man dafür anscheinend die Admin Rolle in der org, ob du die kriegst muss Markus entscheiden

**Comment by d135-1r43** [comment]
Dann setze ich das Credential. Bitte melde dich im Slack und wir regeln das… @MatthiasRaimann

**Comment by MatthiasRaimann** [comment]
Anleitung: https://docs.sonarsource.com/sonarcloud/advanced-setup/ci-based-analysis/sonarscanner-for-maven/#server-organization-and-project
