### ISSUE TITLE
Testdaten für Org Service

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#141]
# User-Story

**Als Entwickler** möchte ich sinnvolle und konsistente Testdaten im org Service zur Verfügung haben, um eine effiziente und realitätsnahe Entwicklung sicherzustellen.

## Akzeptanzkriterien

1. **Automatische Bereitstellung der Testdaten**  
   - Testdaten werden automatisch beim Start des org Service geladen, ohne dass ein manueller Import notwendig ist. Dazu wird eine `import.sql` verwendet, wie in der [Quarkus-Dokumentation zur Hibernate-ORM](https://quarkus.io/guides/hibernate-orm) beschrieben.

2. **Testdaten im Produktionsprofil**  
   - Die Testdaten sind auch im Produktionsprofil (`prod`-Profil) verfügbar, um konsistente Daten in allen Umgebungen sicherzustellen, die nicht auf eine spezifische Entwicklungsumgebung beschränkt sind.

3. **Einheitliche Testdaten für Unit-Tests**  
   - Dieselben Testdaten werden auch in den Unittests verwendet, um eine einheitliche Basis für alle Tests zu gewährleisten und die Wartbarkeit der Tests zu verbessern.

4. **Kompatibilität der Keycloak-Testdaten**  
   - Der Dev Service für Keycloak startet ebenfalls mit vorab konfigurierten Testdaten, die mit den Testdaten des org Service kompatibel sind. Dadurch ist die Authentifizierung in der Entwicklungsumgebung reibungslos und konsistent.

**Comment by schitcrafter** [comment]
Zu 2.: Soll dafür extra Funktionalität bereit stehen, um das Einspielen der Daten einfacher zu machen, oder ist es okay wenn der Prozess ein wenig umständlicher ist (z.B. sql-Skript in der Datenbank ausführen lassen)?

**Comment by 3thr3n** [comment]
Vorschlag:
Können wir das nicht über Flyway regeln?
Ein Ordner in den Resourcen für Testdaten flyway migrationen? 
Dann kann man diesen mit ausgeben und wenn man möchte passt man den key `quarkus.flyway.locations` an und inkludiert den ordner.

**Comment by d135-1r43** [comment]
Wenn wir es so hinkriegen, dass die Testdaten nur in DEV und TEST haben?

**Comment by schitcrafter** [comment]
In DEV sind die Testdaten kein Problem, der Teil ist schon fertig. TEST wird schwieriger, weil die Datenbank, um Nebeneffekte zwischen Tests zu verhindern, vor jedem Test geleert wird, und ich weiß keine Möglichkeit um die `import.sql` (die ich jetzt genutzt habe) wieder einzuspielen. PROD hat das gleiche Problem, da könnte man allerdings per `psql` die SQL-Datei manuell importieren.

Ich werde nach Möglichkeiten für TEST schauen, aber für mich wäre wichtig zu wissen ob die Möglichkeit in PROD mit psql gut genug ist, oder ob es extra Funktionaliät geben soll (z.B. ein REST endpoint o.ä.)

**Comment by d135-1r43** [comment]
Gute Idee, das mache ich inzwischen auch um die Datenbank sauber zu leeren. Etwa so:

```Java
 @Inject
  Flyway flyway;

  @BeforeEach
  public void cleanDatabase() {
      flyway.clean();  // Clears the database
      flyway.migrate();  // Re-applies the migrations
  }
```
