### ISSUE TITLE
Multi Tenant für Bommel

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#145]
# Story

Das System muss in der Lage sein, Bommels für mehrere Mandanten (Multimandanten-Unterstützung) zu verwalten. Jeder Bommel soll eindeutig einem spezifischen Verein zugeordnet sein, sodass keine Überschneidungen zwischen den Mandanten entstehen. Jeder Verein verwaltet eine eigene, strukturierte Bommel-Hierarchie in Form eines Baums, die unabhängig von anderen Vereinen funktioniert.

# Akzeptanzkriterien:

* Ein Bommel kann einem Verein eindeutig zugeordnet werden und ist nur innerhalb dieses Vereins sichtbar.
* Änderungen in der Bommel-Struktur eines Vereins beeinflussen keine anderen Vereine.
* Multimandantenfähigkeit: Das System erlaubt die parallele Verwaltung von Bommeln für mehrere Vereine.

**Comment by 98jan** [comment]
Keycloak hat seit ca. 2 Monaten auch offiziellen Support für Organisationen, planen wir schon eine Integration mit dem Keycloak-Feature oder bauen wir die Logik selbst?

**Comment by d135-1r43** [comment]
Bauen wir erstmal selbst.
