### ISSUE TITLE
GitHub Actions Build für Backend

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#15]
# Story

Als Developer haben wir eine CI/CD. 

# Akzeptanzkriterien

- Jeder Commit wird mindestens mit `mvn clean package` als Java Artefakt gebaut. Optional soll ein Branch auch ein Docker Image bauen können. 
- `main` baut zudem ein Docker Image und pusht dieses in die GitHub Container Registry, der Zugriff ist public.
- Der Name und  Tag der Images ist, wobei `$projektname` mit dem Namen aus https://github.com/Vereinsfin/vereinsfin/issues/2 ersetzt werden soll. 
    - `$projektname/$maven-artifact-id:n`, wobei `n` eine fotlaufende Nummer ist, genau dann wenn HEAD keinen Versionstag für `$maven-articat-id` hat. 
    - `$projektname/$maven-artifact-id:$version`, wobei `$version` eine Semver-Version wie `1.2.3`. ist, genau dann wenn `HEAD` einen Versionstag (z. Bsp. `verein-1.0.0`) hat. 
- die YAML ist gut lesbar, sprechend und sauber gelintet. 

# Hintergrundinformationen

@d135-1r43 hat dieses Setup bereits für Jenkins gebaut und steht für Fragen zur Verfügung.

**Comment by schitcrafter** [comment]
Ich hab ein paar Fragen:

Wie soll ein branch einen container bauen können?

Soll dieser container auf die registry gepusht werden?

Wenn auf main ein commit und ein tag der auf diesen commit zeigt gepusht wird, darf nur ein container gebaut werden? Oder können auch zwei container, einer mit hochlaufender Nummer und einer mit Version gebaut werden?

**Comment by d135-1r43** [comment]
> Wie soll ein branch einen container bauen können?

Damit meinte ich einen Commit auf einem Branch. Also wenn ich auf `feature/my-branch` pushe, dann will ich zumindest manuell ein Image gebaut und gepusht bekommen, um es lokal oder auf einem Server testen zu können. Sonst könnten wir ja nur testen und deployen, was auf `main` ist. 

>Soll dieser container auf die registry gepusht werden?

Ja, die Images sollen auf die GitHub Registry gepusht werden.

**Comment by schitcrafter** [comment]
Hmm, okay. Dann mach ich es so das auf `feature/my-branch` ein container mit tag (z.B.) `feature-my-branch` gepusht wird - ein neuer commit auf dem branch überschreibt dann den vorherigen container

**Comment by d135-1r43** [comment]
Ja, das ist gut.

**Comment by schitcrafter** [comment]
Wie genau sollen die container heißen? Die Namen müssen den prefix `ghcr.io/vereinsfin/vereinsfin` haben, weil des zu unserem repository passt. Danach könnte man jetzt z.B. `/backend` packen, ich denke mal du meintest mit der artifact id die artifact id von dem inneren maven project, also `/vereine`?

**Comment by d135-1r43** [comment]
Genau, die Artifact ID aus der `pom.xml`. In scope von diesem Ticket ist nur Java mit Maven. Stell dich auch drauf ein, dass es ab heute Abend einen komplett neuen Namen gibt, also nicht mehr "vereinsfin".

**Comment by schitcrafter** [comment]
Es gibt zwei `pom.xml`, eine mit `vereine` als artifact id und eine mit `vereinsfin` als artifact id - ich nimm davon jetzt einfach vereine weil des des einzige ist des Sinn macht.

**Comment by schitcrafter** [comment]
https://github.com/hopps-app/hopps/pkgs/container/hopps%2Fvereine/259636656?tag=backend-ci-cd

Erster container mitm (wahrscheinlich) fertigen Namen `ghcr.io/hopps-app/hopps/vereine:backend-ci-cd` ist gepusht, es sind noch zwei andere unter dem alten Namen mit z.T. kaputten tags auf ghcr.io, da müsstest du schauen ob man die löschen kann.

Container sollten funktionieren, habs kurz probiert, http server läuft und nimmt connections an (ich kenn allerdings keine Routen die ich probieren könnte, keine Erfahrung mit kogito).
