### ISSUE TITLE
Vereins Backend ist als Hallo Welt deployed

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#16]
# Story

Der Service "vereine" ist auf unserem Hetzner-Server deployed und beantwortet HTTP Requests

# Akzeptanzkriterien

- Der Service antwortet, wenn er über die IP und den richtigen Port per HTTP aufgerufen wird.
- Der Service ist über Portainer deyployed
- Portainer nutzt den GitHub Login via OAuth2, alle Mitglieder des Teams können sich einloggen. 
- Die Docker Compose kommt aus unserem Git Monorepo und ist clean, minimalistisch und gelintet. 

# Out of Scope

- HTTP
- Proxy

# Hintergrundinformationen

- @d135-1r43 kann Zugriff zum Server geben, nur via SSH-Keys, kein Passwort
- https://github.com/d135-1r43/portainer-easy-setup kann hilfreich sein, muss aber vermutlich geupdated werden. Gerne PR.

**Comment by d135-1r43** [comment]
Ist grad verblockt, bis wir wieder Zugang zu Hetzner haben. @manuelhummler und ich sind dran.

**Comment by D4ykoo** [comment]
GitHub nutzt Developer OAuth Applications um als OIDC Provider zu fungieren. Die Application mit Client-ID sowie dem Secret wurden mittels meinem GitHub Account erstellt. 
Damit die Application weiterhin valid ist und in die Orginasation kommt ist ein Transfer angestoßen.
Dieser muss von @d135-1r43 oder @manuelhummler akzeptiert ist.

**Comment by d135-1r43** [comment]
Hast du konkrete Info, was ich wo machen muss? Am besten mit Link?

**Comment by D4ykoo** [comment]
[Hier](https://docs.github.com/en/enterprise-cloud@latest/apps/oauth-apps/maintaining-oauth-apps/transferring-ownership-of-an-oauth-app) habe ich etwas gefunden. Unter Punkt 8 steht es beschrieben.

**Comment by d135-1r43** [comment]
Ich verstehe noch nicht wofür der OAuth Service benötigt wird. Für den Zugriff von Portainer auf die Container Registry von GitHub?

**Comment by D4ykoo** [comment]
Die OAuth App wird für das folgende Akzeptanzkriterium benötigt: 
* Portainer nutzt den GitHub Login via OAuth2, alle Mitglieder des Teams können sich einloggen.

Hierfür habe ich auch Informationen im [Wiki hinterlegt](https://github.com/hopps-app/hopps/wiki/Infrastruktur#oauth-github-credentials)

**Comment by d135-1r43** [comment]
Jetzt bin ich im Bilde. Danke. Es ist erstmal okay, wenn der Client in deinem Namespace läuft.
