### ISSUE TITLE
Can not create rootBommel anymore

### ISSUE THREAD

**Issue by kzamurnyak** [hopps-app/hopps#196]
creating new root Bommel  is not possible anymore. Also, i think would be more correct if we automatically create rootBommel on the backend after creating organization
![Image](https://github.com/user-attachments/assets/2b50ecb0-9052-4047-8514-79da5d3983ca)
![Image](https://github.com/user-attachments/assets/d68c9560-8674-4613-b9cb-416206d5b222)

**Comment by byte-sized-emi** [comment]
Please include exactly what you did, with the HTTP body, otherwise I can't diagnose this

**Comment by d135-1r43** [comment]
It is always best to "copy as CURL" and post it here.

**Comment by d135-1r43** [comment]
I think you do not have to create the root bommel any longer. See this test:

https://github.com/hopps-app/hopps/blob/66486f4bd3d99128d1f62a2d7ba3b9e942cef4a3/backend/app.hopps.org/src/test/java/app/hopps/org/delegates/PersistOrganizationDelegateTests.java#L40

It should be created automatically and no longe being managed by the frontend. Does this help?
