### ISSUE TITLE
Add password field for NewOrganizationInput to set user password.

### ISSUE THREAD

**Issue by kzamurnyak** [hopps-app/hopps#197]
Currently user can not login after creating organization. We need to fix that. So, pls add password input to NewOrganizationInput and set this password for keycloak user:
![Image](https://github.com/user-attachments/assets/27166c75-d72e-40f0-bd85-ba86819c2e26)

**Comment by d135-1r43** [comment]
True. This feature is missing. I will try to implement it now…
