### ISSUE TITLE
Update `organisation/validate` endpoint to make it usable

### ISSUE THREAD

**Issue by kzamurnyak** [hopps-app/hopps#198]
'organization/validate' expoint currently not usable as there no way to validate fileds which we send when creating new organization. for example, there create organization input fields:
![Image](https://github.com/user-attachments/assets/5566d4fa-59f3-4d09-8e73-c86a1b63eceb)

and here the validation: 
{
  "name": "O",
  "slug": "3xo2ct12f4hjjeq7pgy46onhxo0rz4svb4ye0r480ng12zzfvmro3honmpso1xdn6e78ann3unogab408d5b",
  "type": "EINGETRAGENER_VEREIN",
  "address": {
    "street": "string",
    "number": "string",
    "city": "string",
    "plz": "string",
    "additionalLine": "string"
  },
  "rootBommel": {
    "id": 9007199254740991,
    "name": "string",
    "emoji": "string",
    "responsibleMember": {
      "id": 9007199254740991,
      "firstName": "9",
      "lastName": "G",
      "email": "{",
      "organizations": [
        "string"
      ]
    },
    "organization": "string",
    "parent": "string",
    "children": [
      "string"
    ]
  },
  "members": [
    {
      "id": 9007199254740991,
      "firstName": "r",
      "lastName": "I",
      "email": "A",
      "organizations": [
        "string"
      ]
    }
  ],
  "website": "string",
  "profilePicture": "string",
  "id": 9007199254740991
}

**Comment by kzamurnyak** [comment]
it's not prioritized atm

**Comment by d135-1r43** [comment]
This was a bug from the inner circle of hell. We fucked up the operationIDs in the OpenAPI doc, so the error was just in the Swagger UI, not with the real endpoint. Heisenbug. 

Fixed with the attached PR.
