### ISSUE TITLE
Installation Guide?

### ISSUE THREAD

**Issue by jotwg** [hopps-app/hopps#204]
Hallo,

ich würde mir das Ganze gerne mal lokal aufsetzen, so aus dem Stand gelingt mir das aber nicht.

Gibt es evtl. eine knappe Kurzanleitung, was bei der Konfiguration zu beachten/anzupassen ist?

Vielen Dank und schöne Grüße

**Comment by d135-1r43** [comment]
Wir sind gerade noch knietief in der Entwicklung und haben noch kein Release fertig. Geht es dir um ein Developer-Setup? Da könnten wir helfen. Produktiv nutzen kann man Hopps gerade aber noch nicht.

**Comment by jotwg** [comment]
danke für die prompte Antwort!

Ja, Developer-Setup wäre prima. 

Grüße
Jörg

**Comment by byte-sized-emi** [comment]
Schau mal in https://github.com/hopps-app/hopps/blob/main/infrastructure/hopps-app/docker-compose.yaml, die sollte für ein dev setup (ohne frontend momentan) ausreichen. frontend kann man aber sicher auch so aufsetzen, wie genau weiß ich nicht

**Comment by jotwg** [comment]
ja, soweit klar, ich hänge beim keycloak und dem nginx-proxy-manager...
Bei letzterem würde mir helfen, wenn ich wüsste, welche proxy hosts ich genau einrichten muss.

Danke & Grüße
Jörg

**Comment by byte-sized-emi** [comment]
Welchen nginx-proxy-manager meinst du genau? In der docker-compose ist keiner, sollte für lokales dev setup auch nicht nötig sein

**Comment by jotwg** [comment]
ja, ich dachte, der wird für die Kommunikation container untereinander gebraucht, war Quatsch gedacht, sorry.

Habe inzwischen das front end soweit am laufen (zunächst alles unter localhost), dass es beim login zu keycloak geht (config in .env fehlte und das front end muss auf einen anderen Port als 8080) und die beiden Test User (alice und bob) sich anmelden können, dann geht es aber zurück auf die ursprünliche URL und es passiert weiter nix!?

Und: die keycloak themes habe ich nach README gebaut bekommen, weiß aber nicht, wie ich die in den keycloak reinbringe!?

Danke&Grüße
Jörg

**Comment by byte-sized-emi** [comment]
Du müsstest den frontend fehler wahrscheinlich genauer beschreiben damit sich da jemand drum kümmern kann. Ich kenn miich damit sowieso nicht aus, habs mal in den internen slack geschrieben, vielleicht hat jemand Zeit. Hab aber bitte Verständnis dafür das wir nicht viel Zeit haben und uns deswegen tendenziell mehr auf die Entwicklung konzentrieren - wenn Hopps mal näherungsweise fertig ist wird es auch einfacher, das Projekt lokal zu starten.

Keycloak themes hört sich nach einem rein optischen Thema aus, wenn es dir erstmal um ein dev-setup geht könntest du das auch skippen.

**Comment by jotwg** [comment]
selbstverständlich will ich Euch nicht aufhalten und kann warten...

Danke für die Antworten und guten Erfolg!
