### ISSUE TITLE
Arbeitsverträge

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#21]
# Story

Alle Minijobber haben einen sauberen Arbeitsvertrag

# Akzeptanzkriterien

- Vertrag hat eine Vorlage (siehe Slack) als Grundlage
- Verträge sind von allen Arbeitenden unterschrieben und damit rechtsgültig

**Comment by manuelhummler** [comment]
Der aktuelle Stand kann eingesehen werden im Internen Vorstands Ordner von Open Project, da es sich hier um Personaldaten handelt. Bei Zugriffsanfragen wende dich gerne an @blackwolfk-9  oder mich. Von allen Personen, die einen Arbeitsvertrag möchten hat aktuell eine Person noch keinen bekommen. Ansonsten überarbeiten wir gerade nochmal die Arbeitsverträge und legen ein paar grundlegende Dinge fest. z.B. inwieweit wir flexible Arbeitsverträge anbieten wollen, oder ob wir hier immer ein gewisses Commitment sehen möchten und ein Festlegen auf eine Stundenzahl/Woche. Natürlich weiterhin mit der Flexibilität eines Stundenkontos. Hier erstellen wir eine Pro und Kontra Liste, um darüber entscheiden zu können. Dazu haben Jannik und ich am Dienstag ab 18:00 Uhr ein Meeting angesetzt um das ganze auszuarbeiten und uns bis dahin schonmal Gedanken zu machen. Wir haben nämlich aktuell sehr viele Personen, die gerne flexibel Arbeiten möchten, allerdings sehen wir auch viele Vorteile für das Projekt bei festglegten Zeiten.

**Comment by manuelhummler** [comment]
@sk2675
