### ISSUE TITLE
As a frontend developer i can not get my current organization after login

### ISSUE THREAD

**Issue by kzamurnyak** [hopps-app/hopps#220]
So, from the dev experience i should be able to get my current user organization from the backend. Currently it's not possible because I've able to just fetch organization by slug (what i did by hardcoding).
So, it's kind of blocker for me and would be nice to improve that...

**Comment by d135-1r43** [comment]
Will do it, should be a simple fix…

**Comment by d135-1r43** [comment]
It works on the branch with a new endpoint `/organizations/my`, but it is not merged yet.
