### ISSUE TITLE
Setup der Azure Plattform

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#26]
# Story

Als Entwickler von Hopps bin ich in der Lage, den AI Document Intelligence Service von Microsoft Azure in meiner täglichen Entwicklung für Hopps zu nutzen. 

# Akzeptanzkriterien

* Das Produkt ist https://azure.microsoft.com/de-de/products/ai-services/ai-document-intelligence
* Soll über Open Source bzw. Non Profit Budget-Spende von Azure erfolgen, was auch sauber dokumentiert werden muss für unsere Nachweise
* Die Bezahlung erfolgt direkt durch Open Project e.V.
* Es gibt einen dokumentierten Prozess, wie man an das Token kommt, z. Bsp. im noch zu erstellenden Wiki. 
* Für das Produktive Deployment muss es möglich sein, über ENV-Vars den Zugang des Hopps Services zu Microsoft Azure AI Document Intelligence zu erlangen. 
* Kostenpflichtige Resourcen in Azure nutzen zuerst das Budget von 2000$ jährlich auf, bevor auf Zahlungen zurückgegriffen wird
* Die beanspruchte Summe des Azure Guthabens ist dokumentiert und in der Buchhaltung für das Projekt als Spende kategorisiert
* Wenn das Budget überschritten wird sollen @sk2675 @manuelhummler oder @d135-1r43 benachrichtigt werden
* Eine Obergrenze bei Überschreitung des Budgets ist festgelegt, die nicht überschritten werden darf
* Bei einer Überschreitung von maximal 1000€ findet keine Beeinträchtigung der Services statt

**Comment by d135-1r43** [comment]
@sk2675, wie ist hier der Stand? @schitcrafter arbeitet bereits an dem Service.

**Comment by schitcrafter** [comment]
Wäre wichtig das wir eine Azure Subscription haben, ist für mich momentan ein Blocker.

**Comment by manuelhummler** [comment]
@schitcrafter du solltest auch die Berechtigunge haben eine anzulegen. Bitte aber darauf achten, dass entsprechend die 2000$ da irgendwie zugewiesen werden 😄

**Comment by schitcrafter** [comment]
Hab nichts gefunden dazu, per der Azure Dokumentation für non profits kriegt die Person die des Geld angefragt hat eine Email mit der man die subscription buchen kann - siehe den Link im slack Privatchat

**Comment by manuelhummler** [comment]
noch nicht dokumentiert, daher nochmal zurück in "In Progress" 
shameee

**Comment by d135-1r43** [comment]
@schitcrafter, funktioniert es für dich? Wenn ja, dann würde ich das Ticket so akzeptieren.

**Comment by schitcrafter** [comment]
Azure funktioniert super für mich
