### ISSUE TITLE
Allcontributors im Mono-Repo

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#29]
# Story

Das Monorepo https://github.com/hopps-app/hopps hat in der `README.md` einen Absatz mit allen Contributors, um diese wertzuschätzen. 

# Akzeptanzkriterien

* Wir benutzen [allcontributors.org](https://allcontributors.org/)
* Das Hinzufügen von Kacheln erfolgt über automatisierte MRs
* Der Absatz ist ganz unten in der `README.md`

**Comment by schitcrafter** [comment]
@all-contributors please add @schitcrafter for tools

**Comment by schitcrafter** [comment]
@d135-1r43 soll ich in der README.md eine Sektion hinzufügen die links zur allcontributors doku gibt, damit contributors sehen können wie sie sich hinzufügen können?

**Comment by d135-1r43** [comment]
@schitcrafter: Ja, bitte.

**Comment by d135-1r43** [comment]
@all-contributors Add @d135-1r43 for code and business
