### ISSUE TITLE
Logo, Typografie und Farbschema

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#3]
# Story

Das Produkt hat ein Logo, ein Farbschema und definierte Hausschriften.

# Akzeptanzkriterien

- Es werden mindestens 3 Konzepte ausgearbeitet und im Team vorgestellt. Die Konzepte verfolgen unterschiedliche Stile und Ansätze.
- Basis der Konzepte ist ein im Team abgestimmtes Moodboard. 
- Die Vorstellung erfolgt in Form einer Konzeptmappe mit UX Mockups, verschiedenen Darstellungen und Erklärungen als PDF
- Das Logo funktioniert in verschiedenen Größen (Favicon, Aufkleber, Hero Image) und in verschiedenen Medien
- Das Logo ist arty, modern, zeitgemäß, besonders, nicht "Enterprise"
- Das Logo wird als Vektorgrafik erstellt, um Skalierbarkeit ohne Qualitätsverlust zu gewährleisten
- Die verwendeten Farben sind in Form von RGB Werten eindeutig definiert
- Die Schriften sind unter einer freien Lizenz lizensiert, sodass sie gemeinsam mit dem MIT lizensierten Produkt ausgeliefert werden können. Präferiert ist hier die [SIL](https://de.wikipedia.org/wiki/SIL_Open_Font_License).
- Entweder ein Font-Pairing mit einer Schrift für Fließtexte und eine für Display oder ein variabler Font, der für alles nutzbar ist. 
- Eine Feedback-Runde mit einer kleinen Gruppe von Zielkunden oder Stakeholdern wird durchgeführt, um sicherzustellen, dass das Design gut ankommt und verstanden wird
- Iterative Anpassungen werden basierend auf dem Feedback vorgenommen

**Comment by d135-1r43** [comment]
Verblockt von https://github.com/Vereinsfin/vereinsfin/issues/2

**Comment by sk2675** [comment]
Hier einer der ersten Ideen für den Name des Tools:

[]()https://docs.google.com/presentation/d/1Y8omLRdhHdBm-4bTB7J2enq4y3OPq2tvd_1mH9ikuc4/edit?usp=drivesdk

**Comment by d135-1r43** [comment]
Name ist gefunden: "Hopps"

Jetzt kann es hier losgehen!

**Comment by d135-1r43** [comment]
@sk2675, wie ist hier der Stand? Das Thema verblockt grad ziemlich viele andere Tickets.

**Comment by sk2675** [comment]
Deadline ist 30.09.2024

**Comment by d135-1r43** [comment]
Wird zum 30.09. geliefert oder ist da auch schon die erste Feedbackrunde durch?

**Comment by lukas-leonhardt** [comment]
> Wird zum 30.09. geliefert oder ist da auch schon die erste Feedbackrunde durch?

Ich schlage vor, dass wir zeitnah/vor 30.09. bereits einen Schulterblick machen. Dann können wir das Feedback gleich einarbeiten/nochmal andere Ansätze explorieren falls nötig. In welcher Runde machen wir das am besten? Zeitlich am besten mal am Abend, da Rabea in Neuseeland ist und Zeitverschiebung hat.

**Comment by d135-1r43** [comment]
Ich würde sagen mit @d135-1r43, @eliashehme, @sk2675 und @manuelhummler.

**Comment by sk2675** [comment]
Ich würde diesen Termin extern machen. Wenn nur wir teilnehmen sollen, @d135-1r43 entscheide du!

**Comment by d135-1r43** [comment]
Ja, extern. Planung grad im Slack.
