### ISSUE TITLE
Webseite

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#32]
# Story

Das Produkt hat eine Webseite. 

# Akzeptanzkriterien

- Vorerst nur eine einfache Visitenkarte mit Logo und kurzer Beschreibung
- Korrektes Impressum
- keine Third-Party Cookies, kein Cookie-Banner
- Im CI mit Logo, Farben und Schrift
- Passende Domain
- Leitungsteam hat Zugriff auf die Zugangsdaten

**Comment by d135-1r43** [comment]
Hier müssen wir warten, bis #3 final ist.

**Comment by sk2675** [comment]
Ja, passt. 👍🏻

**Comment by d135-1r43** [comment]
Es gibt jetzt #87, welches besser spezifiziert ist. Ich schließe daher dieses Issue als Duplikat.
