### ISSUE TITLE
3rd Party S3

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#35]
# Story

Als Entwickler steht ein externer S3 kompatibler Object Storage zur Verfügung, um dort Backups zu speichern. 

# Akzeptanzkriterien

* Ein Bucket mit einem sinnvollen Namen im app.hoops Namespace
* Hosted at Digital Ocean at the lowest, e.g. cheapest tier. 
* Bezahlt von gespendetem Guthaben (@manuelhummler hat den Überblick)

**Comment by eliashehme** [comment]
Ich hätte jetzt den Anbieter Azure Blob Storage gewählt. Nicht nur weil er gut in Microsoft-Dienste integriert ist, sondern weil wir sowie so eine Azure-Konto benötigen und es somit kosteneffektiv ist.

**Comment by eliashehme** [comment]
Als Namen hatte ich jetzt an app.hoops.backups gedacht.

**Comment by manuelhummler** [comment]
@eliashehme Blobstorage würde für mich passen. Damit habe ich auch schon einiges gemacht und kann wenns ist auch unterstützen. Soweit ich das weiß, ist der allerdings nicht out of the Box S3 kompatibel, kann aber wohl mit Flexify.IO nachgerüstet werden:

https://azuremarketplace.microsoft.com/de-de/marketplace/apps/flexify.azure-s3-api?tab=overview

**Comment by d135-1r43** [comment]
We pivot to Digital Ocean and sundown the setup at Azure.

**Comment by manuelhummler** [comment]
Ich habe Digital Ocean aufgesetzt und die Mariadb, wo unser Zeiterfassungstool läuft wird hier bereits bereits automatisch jede nacht gebackupt. 

![Image](https://github.com/user-attachments/assets/6774ed7d-376a-4773-bb27-3c440df9fb2b)

Ich dokumentiere das ganze noch.

**Comment by manuelhummler** [comment]
Microsoft Azure habe ich aufgeräumt und folgende Resourcen wieder gelöscht. (Krass was da alles mitgekommen ist)

![Image](https://github.com/user-attachments/assets/d3023153-82b7-4dfa-9db6-e5a88f91d707)

**Comment by d135-1r43** [comment]
Passt. Damit erledigt. Danke.
