### ISSUE TITLE
Markenanmeldung für Deutschland

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#37]
# Story

"Hopps" ist über einen Onlinedienst als Marke angemeldet

# Akzeptanzkriterien

* Ein geeignerter Service ist ausgewählt
* Das Angebot und die Kosten sind von  @d135-1r43 und @manuelhummler freigegeben. 
* Die Anmeldung über den Service hat nachweislich stattgefunden.

**Comment by d135-1r43** [comment]
Wie ist hier der Stand?

**Comment by manuelhummler** [comment]
@d135-1r43 : @eliashehme und ich haben gestern die Anmeldung abgeschickt und bezahlt. Ist also soweit geschehen und wir warten jetzt was passiert. 😄
