### ISSUE TITLE
Figma Account

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#4]
# Story

Dem Produkt-Team stehen Figma-Accounts für das Erstellen von Designs und UX zur Verfügung.

# Akzeptanzkriterien

- Vorab wird überprüft, ob für Non-Profits ein Rabatt oder gratis Accounts möglich sind
- Alle im Produktteam haben einen persönlichen Account und sind zu einem Team zusammengefasst

**Comment by d135-1r43** [comment]
Erste kleine Recherche hat ergeben, dass es keinen Nonprofit-Rabatt gibt.

**Comment by eliashehme** [comment]
Also ich würde uns den Figma Professional Plan für 15 €/unbeschränkte Lizenz/Mon. vorschlagen. Das ermöglicht uns unbegrenzte Projekte zu verwalten und unbegrenzter Zugang für Editoren, Zugang zu erweiterten Prototyping-Tools und die Möglichkeit komplexe Benutzeroberflächen zu gestalten und es gibt die Möglichkeit einen Gast-Zugang und erweiterte Freigabeoptionen freizugeben.

Also ich denke das Preis-Leistungs-Verhältnis ist hier das Beste.

**Comment by d135-1r43** [comment]
Ich nehme an 15€ pro User pro Monat, richtig? Wenn ja, dann bitte mal herausfinden wer im Team "Produkt" eine Lizenz braucht.

**Comment by manuelhummler** [comment]
Ich nicht. Mir reicht die lesende Ansicht. 👍

**Comment by d135-1r43** [comment]
Haben wir gerade eingerichtet für

* @manuelhummler 
* @d135-1r43 
* @RabeaBonten 
* @lukas-leonhardt 
* @eliashehme

**Comment by d135-1r43** [comment]
@all-contributors Add @sk2675 for projectManagement
