### ISSUE TITLE
System zum Austauschen von Credentials

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#40]
# Story

Als berechtigter Entwickler habe ich Zugriff auf wichtige Credentials 

# Akzeptanzkriterien

* Das System ist im besten Fall SaaS und kostenlos nutzbar
* Im besten Fall Log-in mit GitHub OAuth2/OIDC
* Es muss die Möglichkeit geben, Credentials sowohl mit dem ganzen Team als auch mit einzelnen Personen zu teilen
* Die UX soll gut und zugänglich sein. 
* Das System ist installiert, verfügbar, im Wiki dokumentiert und im Slack angekündigt.

**Comment by d135-1r43** [comment]
Vaultwarden it is 🙌

**Comment by d135-1r43** [comment]
@manuelhummler, wollt ihr es mit OIDC absichern oder direkt die eingebaute Benutzerverwaltung nutzen?

**Comment by manuelhummler** [comment]
SSO ist leider bei Vaultwarden noch nicht unterstützt und wird es voraussichtlich vorerst auch nicht, "unless contributed"
https://github.com/dani-garcia/vaultwarden/wiki#missing-features
Daher würde ich die Nutzerverwaltung intern so wie sie ist nutzen @d135-1r43 😄

**Comment by d135-1r43** [comment]
Voll okay. Machen wir bei EXP auch so. Dokumentierst du dann noch?

**Comment by manuelhummler** [comment]
@d135-1r43 yes, mache ich 👍

**Comment by manuelhummler** [comment]
@d135-1r43 Dokumentation kann hier gefunden werden:
https://openprojectpaf.sharepoint.com/:b:/s/hopps/EStqCHmBE6JCqLxOJTSJ_ykBC3ejgdvYrVG4xFqvFIcnpA?e=eHca4w

**Comment by d135-1r43** [comment]
Danke. Kannst du in der Dokumentation bitte noch die Person konkret benennen, die Accounts anlegen kann?

**Comment by manuelhummler** [comment]
@d135-1r43 habe Jannik und mich hier ergänzt
