### ISSUE TITLE
Detaillierter Budgetplan

### ISSUE THREAD

**Issue by eliashehme** [hopps-app/hopps#44]
# Story

Dem Leitungsteam liegt ein detaillierter Budgeplan vor. 

# Akzeptanzkriterien

- Der Budgetplan ist konform mit dem Antrag
- Er setzt monatliche Budgets
- Er erlaubt einen IST/SOLL-Vergleich
- Einfache, pragmatische Lösung, etwa Google Docs oder Excel

**Comment by manuelhummler** [comment]
@eliashehme vernetz dich bitte mit @blackwolfk-9 
Er unterstützt hier auch. 😄

**Comment by d135-1r43** [comment]
@all-contributors add @eliashehme for projectManagement and business
