### ISSUE TITLE
Lohnabrechnung

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#5]
# Story

Eine Lohnabrechnung für die Teilnehmenden ist installiert und aktiv.

# Akzeptanzkriterien

- Eine ausführliche Recherche über den richtigen Modus (Ehrenamtspauschale, Minijob, selbstständig, etc.) hat stattgefunden und das Ergebnis wurde dokumentiert und durch einen Experten validiert
- Ein einfaches und pragmatisches System zur monatlichen Auszahlung ist implementiert, ggf. auch komplett manuell
- Die steuerlichen Aspekte sind vollständig geklärt und von einem Experten validiert
- Die Buchhaltung ist transparent und für das gesamte Leitungsteam zugänglich. Alle relevanten Daten und Prozesse sind dokumentiert
- Das Auszahlungssystem gewährleistet die regelmäßige und pünktliche Auszahlung der Löhne
- Sicherheitsmaßnahmen sind implementiert, um die Vertraulichkeit und Integrität der Lohnabrechnungsdaten zu gewährleisten

**Comment by d135-1r43** [comment]
@manuelhummler Brauchst du das Ticket noch oder können wir es vom Produkbacklog runter nehmen?

**Comment by manuelhummler** [comment]
@d135-1r43 können wir runter nehmen.
