### ISSUE TITLE
Prozess für Auslagen-Workflow

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#50]
# Userstory (nur BPMN)

Als Mitglied eines Vereins lade ich einen Kassenzettel hoch, bestätige das Ergebnis der AI-Kassenbon-Erkennung und schicke den Bon ab zu meinem Kassier des Vereins. Dieser bestätigt die Auslage. Wenn ich meine Kontodaten hinterlegt habe, wird mir das Geld sofort erstattet. 

# Akzeptanzkriterien

* Nur BPMN Workflow als BPMN Diagramm, welches eine Anlage an dieses Issue ist. 
* Camunda Modeller oder Kogito Modeller in Visual Studio Code
* Stilistisch sauberes BPMN

**Comment by manuelhummler** [comment]
@d135-1r43 

Was soll passieren, wenn der Kassier den Bon nicht bestätigt? Welche anderen alternativen gibt es, außer bestätigen?
Was passiert, wenn ich meine Kontodaten nicht hinterlegt habe?

**Comment by d135-1r43** [comment]
- Wenn der Bon nicht bestätigt wird, dann erfolgt keine Erstattung und keine Verbuchung. Der Kassier muss einen Grund angeben und das Mitglied bekommt diesen Grund als Nachricht. Dann ist der Prozess zu Ende. 
- Wenn keine Kontodaten hinterlegt sind, dann bekommt das Mitglied eine Usertask, sein Konto zu hinterlegen.
