### ISSUE TITLE
Hallo Welt Android

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#52]
# Userstory

Als PO habe ich die Hopps App auf meinem Android Phone. 

# Akzeptanzkriterien

* nur eine Hallo Welt App in React Native
* Komplette CI/CD inkl. Google Play Public Beta
* @d135-1r43  kann die App auf seinem Android Phone starten

**Comment by manuelhummler** [comment]
https://expo.dev/accounts/hopps/projects/hopps/builds/93d94189-a5c7-4342-9864-cf84a660b91e

Da Google Play rausfällt hier schonmal zum testen. Damit kannst du die generierte preview apk herunterladen @d135-1r43 
Aktuell noch komplett so wie initial aufgesetzt

Die CI/CD bitte in ein Extra Ticket packen, dann kümmere ich mich da auch noch bei Gelegenheit darum.

**Comment by d135-1r43** [comment]
Passt, die App läuft.
