### ISSUE TITLE
Einsammeln von Test-Belegen

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#54]
# Story

Als Entwickler habe ich ein Set von ca. 30 Bilddateien und PDFs, die eine gute Abdeckung von allen möglichen Belegarten und Qualitäten darstellen. 

# Akzeptanzkriterien
- Einfache Belege ohne Kreditor-Adresse, z. Bsp. Aldi, Kaufland, Bäcker, Pizzalieferdienst
- schlecht fotografierte Belege (verblasst, zerknittert, schlechte Kamera)
- sehr gute PDFs, z. Bsp. von Amazon
- abgelegt im Google Drive

**Comment by eliashehme** [comment]
https://drive.google.com/drive/folders/1rJjzaffP4EowbGqdaiZJRkTQrN3gRlgJ?usp=sharing

**Comment by d135-1r43** [comment]
Ist soweit fein, danke. 

@eliashehme, bitte die Tickets nicht selbst schließen. Die finale Abnahme muss ich als PO machen.
