### ISSUE TITLE
Azure Form AI Service

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#55]
# Story

Als Entwickler habe ich einen Service zur Verfügung, der Cloudevents per Kafka entgegennimmt, um die dort übermittelte Rechnung mit Azure Form AI zu lesen und die Daten wieder als Cloudevent zu publizieren. 

# Akzeptanzkriterien

- separater Quarkus Service
- Abstraktion der Cloudevents über die Konfiguration vom Channel)
- inkl. CI/CD bis hin zum Docker Image

**Comment by schitcrafter** [comment]
@d135-1r43 du hast gesagt das es eine bessere Integration von cloudevents in kafka gibt als in https://quarkus.io/blog/kafka-cloud-events/ beschrieben, könntest du mir bitte einen Link o.ä. dafür geben?

**Comment by d135-1r43** [comment]
Das ist echt total schlecht dokumentiert. Ein bisschen was steht bei der Smallrye Implementierung: 

https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.4/kafka/kafka.html#_receiving_cloud_events

Und wenn du nach `cloud-event` suchst, findest du die passenden Properties, um es zu konfigurieren. Man muss im Code also nix ändern, nur in der `application.properties`. 

![Config Properties](https://github.com/user-attachments/assets/5759f023-623c-4f8c-ad00-dd07e17cdbe1)

**Comment by d135-1r43** [comment]
Und bitte den Service umbenennen in `app.hopps.az-document-ai`. Und im Datenmodell achtgeben, dass nicht alles eine "Invoice" ist. Es kann auch nur ein Beleg sein, also "Receipt" sein. Da braucht es einen Überbegriff. Vielleicht tatsächlich `document`.

**Comment by schitcrafter** [comment]
Auf welcher Seite siehst du die config variablen? Ich finde die nicht, ist nicht die standard quarkus Seite dafür

Und; ist es okay wenn wir im Frontend schon den Nutzer fragen ob es ein Beleg oder eine Rechnung ist? Azure hat models für receipts und invoices, aber soweit ich des sehe nichts um zu entscheiden welches davon ein Dokument genau ist.

**Comment by schitcrafter** [comment]
Wie handeln wir Addressen von z.B. Geschäften? Wir könnten die Information einfach weglassen, strukturiert mitschicken (also JSON-Objekt mit `postalCode`, `city`, etc.) oder irgendwie formatiert als String senden, und ich weiß nicht welches davon momentan am besten ist.

**Comment by schitcrafter** [comment]
Von meiner Seite aus bin ich fertig, du hast die Changes auch approved, ich hätte erwartet das du die Changes dann mergst
