### ISSUE TITLE
Pressemitteilung

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#6]
# Story

Eine Pressemitteilung liegt den lokalen Medien vor.

# Akzeptanzkriterien

- Die Pressemitteilung ist ein Fließtext und diverse Fotos
- Die Mitteilung wird in Abstimmung mit der Stadtjugendpflege an die Presse übergeben
- Die Mitteilung wird vor Abgabe lektoriert
- Quellen von Fotos sind bekannt und benannt
- Alle auf den Fotos dargestellten Personen haben die Einwilligung unterschrieben
- Die Pressemitteilung ist auch über die Webseite von Open Project abrufbar

**Comment by d135-1r43** [comment]
Verblockt von #32 und #3

**Comment by eliashehme** [comment]
Gibt es einen Ansprechpartner für Rückfragen? (Name, E-Mail)

**Comment by eliashehme** [comment]
Erste Version:
https://docs.google.com/document/d/1gMmtq__J4da2WSC3a4aNiK1w9KeECbiM5Q9lFVydjOI/edit?usp=sharing

**Comment by d135-1r43** [comment]
Finde ich soweit gut. Brauchen wir eine zweite PM für die regionale Presse? Und @manuelhummler, kannst du noch ein Zitat von dir spendieren?

**Comment by manuelhummler** [comment]
hab hier Mal drin rumgefriemelt und folgendes Zitat gespendet:

„Das Besondere an diesem Projekt ist, dass viele junge Menschen aktiv mitwirken können. Es hat die Größe und Komplexität eines echten Großprojekts und erfüllt damit den Anspruch des Open Project e.V.: jungen Menschen durch reale Projekte praxisnahe Themen aus der Berufswelt näherzubringen und aktives Lernen sowie Mitwirken zu fördern.“, freut sich der Vorsitzende des Vereins.

**Comment by manuelhummler** [comment]
@d135-1r43 und weil ich gerade so motiviert war, habe ich einfach Mal frei von der Leber weg einen "kleinen" Text für die Lokalpresse geschrieben und einmal durch ChatGPT gejagt. Die Version kann vielleicht noch bisschen persönlicher gemacht werden. Hier ist leider einiges aus meiner ursprünglichen Fassung verloren gegangen. Vielleicht hat hier jemand Lust, ansonsten habe ich auch Jarah darum gebeten nochmal drüber zu schauen.

**Comment by eliashehme** [comment]
Ich habe jetzt die Anmerkungen und kleine Änderungen übernommen.
https://docs.google.com/document/d/1gMmtq__J4da2WSC3a4aNiK1w9KeECbiM5Q9lFVydjOI/edit?usp=sharing

**Comment by manuelhummler** [comment]
@eliashehme super, finde ich gut! 😄

**Comment by d135-1r43** [comment]
Passt, dann brauchen wir jetzt noch Fotos.

**Comment by eliashehme** [comment]
hier Vorschläge für die Fotos:

1. Teamfoto Projektteam
2. Foto einer "Brainstorming-Sitzung" / Meeting

**Comment by d135-1r43** [comment]
Fotos sind gemacht, ich muss sie noch einmal durch Lightroom jagen. Mach ich die Tage…

**Comment by d135-1r43** [comment]
@eliashehme, lass uns das am Samstag gemeinsam machen. Da treffen wir uns ja eh.

**Comment by eliashehme** [comment]
Ich habe die Pressemitteilung verschickt.

**Comment by manuelhummler** [comment]
Nice, spitze! 😄

**Comment by manuelhummler** [comment]
@eliashehme kannst du noch kurz ergänzen an wen alles? 😸

**Comment by eliashehme** [comment]
Pfaffenhofen Today, Pfaffenhofener Kurier, TV Ingolstadt, BR Ingolstadt

**Comment by manuelhummler** [comment]
Ich habe den Presseartikel noch auf Paf und Du hochgeladen: https://www.pafunddu.de/pfaffenhofen/c-freizeit-sport-und-gesundheit/hopps-die-neue-open-source-buchhaltungssoftware-fuer-vereine_a38412
