### ISSUE TITLE
Ausarbeitung Entwurf lila

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#67]
# User Story

**Als** Product Owner (PO)  
**möchte ich** einen ausgearbeiteten Entwurf für eine Landingpage erhalten,
**um** die Marke exemplarisch vorzustellen.

# Akzeptanzkriterien

- Der Entwurf enthält ein Hero-Image, wobei das Bildmaterial entweder selbstständig recherchiert oder auf Anfrage durch den PO bereitgestellt wird.
- Es gibt zwei Textblöcke für Copytext (Erstellung und Integration der Texte erfolgt in einem separaten Ticket).
- Das Menü im Header wird angezeigt, jedoch ohne funktionierende Links.
- Die Footerzeile enthält übliche Inhalte wie Sitemap und Impressum, jedoch als nicht klickbare Links.
- Die Landingpage ist für Desktop- und mobile Ansichten (hochkant) optimiert.

**Comment by d135-1r43** [comment]
Ich habe einige Stockfotos zur Auswahl in den Slack gepostet. Diese sind non-free, daher bitte nicht in Repos mit MIT pushen.

**Comment by lukas-leonhardt** [comment]
Ein Entwurf zur Besprechung der LandingPage lila ist fertig.
https://www.figma.com/design/1GxaXKEiosDy2PnCZXIMhq/Branding?node-id=270-301&t=LBvpK3X7NWUNWYqg-4

**Comment by d135-1r43** [comment]
Ist geil. Passt. 

- Gibt es Konzepte, wie man die Fotos vereinheitlichen kann? Irgendein Style darüber, damit sie konsistenter sind? Ich finde, sie passen nicht so recht zusammen.
- Kannst du noch das aktuelle Logo einbinden? Das mal im Kontext zu sehen, fände ich gut.

**Comment by lukas-leonhardt** [comment]
Ich hab mal den Bilder noch ein 8% Overlay gegeben. Vielleicht ist es schon besser

**Comment by d135-1r43** [comment]
Ich teile die Adobe Library mit dir, siehe Slack.

**Comment by lukas-leonhardt** [comment]
Logo ist jetzt auch drin.

**Comment by d135-1r43** [comment]
Super, passt. Aus meiner Sicht done und abgenommen. Bist du auch zufrieden? :)

**Comment by lukas-leonhardt** [comment]
Yes ich mags - vor allem im Dunkelmodus. Ist mal was anderes und überrascht.

**Comment by d135-1r43** [comment]
@all-contributors add @lukas-leonhardt for design
