### ISSUE TITLE
Ausarbeitung Entwurf gelbgrün

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#68]
# User Story

**Als** Product Owner (PO)  
**möchte ich** einen ausgearbeiteten Entwurf für eine Landingpage erhalten,
**um** die Marke exemplarisch vorzustellen.

# Akzeptanzkriterien

- Der Entwurf enthält ein Hero-Image, wobei das Bildmaterial entweder selbstständig recherchiert oder auf Anfrage durch den PO bereitgestellt wird.
- Es gibt zwei Textblöcke für Copytext (Erstellung und Integration der Texte erfolgt in einem separaten Ticket).
- Das Menü im Header wird angezeigt, jedoch ohne funktionierende Links.
- Die Footerzeile enthält übliche Inhalte wie Sitemap und Impressum, jedoch als nicht klickbare Links.
- Die Landingpage ist für Desktop- und mobile Ansichten (hochkant) optimiert.

**Comment by d135-1r43** [comment]
Ich habe einige Stockfotos zur Auswahl in den Slack gepostet. Diese sind non-free, daher bitte nicht in Repos mit MIT pushen.

**Comment by d135-1r43** [comment]
Gerne einfach hier den Link posten, wir geben dann asynchron und als Kommentar Feedback dazu. Das ist einfacher als extra ein Meeting zu machen.

**Comment by RabeaBonten** [comment]
[Hier der Link zum Grün Gelben Prototypen](https://www.figma.com/design/1GxaXKEiosDy2PnCZXIMhq/Branding?node-id=243-18&t=wecUceH6jI52LQxG-1)

**Comment by d135-1r43** [comment]
@all-contributors add @RabeaBonten  for design
