### ISSUE TITLE
Example: Pushnachricht jeden Morgen

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#70]
# Story

Als Benutzer der mobilen App erhalte ich jeden Morgen eine lustige Push-Nachricht, um daran erinnert zu werden, dass es die App gibt. 

# Akzeptanzkriterien

- Auf iOS und Android soll jeden Morgen eine Pushnachricht auftauchen
- Die Nachricht soll einen lustigen Witz beinhalten
- Die Pushnachrichten werden über einen eigenen Microservice geschickt, welcher auf ein Kafka-Topic "app.hopps.notifications" hört und diese Nachrichten dann über Firebase ausliefert. 
- Die Witze wollen über Langchain4j und OpenAI in Echtzeit generiert werden (jeden Tag ein neuer Witz, immer zum Thema Hase).

**Comment by schitcrafter** [comment]
Ich habe zu dem Issue ein paar Fragen:
 - soll das Feature einen eigenen Microservice haben?
 - Witze hardcoded oder KI-generiert?
