### ISSUE TITLE
Kreditkarte organisieren

### ISSUE THREAD

**Issue by blackwolfk-9** [hopps-app/hopps#72]
# Story

Wir wollen Services wie Azure, OpenAI, etc. mit Kreditkarte bezahlen.

# Akzeptanzkriterien

Es gibt eine Kreditkarte.

**Comment by manuelhummler** [comment]
Warte auf Rückruf des zuständigen Bankmitarbeiters, weil er klären wollte, ob die verantwortliche Kassiererin mit einer Vollmacht die Kreditkarte vor Ort holen kann.
