### ISSUE TITLE
Ordnerstruktur anlegen und Zugriff verwalten auf Teams

### ISSUE THREAD

**Issue by blackwolfk-9** [hopps-app/hopps#73]
# Story

Ein User möchte Zugriff auf ein Dateiablagesystem in dem alle unsere Dateien übersichtlich verwaltet werden 

# Akzeptanzkriterien

- Vertrauliche Daten sind nicht für alle einsehbar
- Jeder hat eine @op-paf Adresse mit Microsoft 365 Zugang
- Alle Dateien wurden vom Google Share Point in Office-Programme übertragen und auf dem Sharepoint abgelegt.

**Comment by manuelhummler** [comment]
https://admin.microsoft.com/AdminPortal/Home#/support/request?requestId=2409301420001504
Ticket bei Microsoft für mehr NonProfit Microsoft 365 Licenses

**Comment by manuelhummler** [comment]
Weitere Lizenzen kosten 5.10€/Monat (ist fair würde ich sagen).

Die Zugriffe sind hier dokumentiert: https://openprojectpaf.sharepoint.com/:f:/s/hopps/ElvN6JakZQJFhi0Maoj3fsgB5oAwxsvcHH-MHQOC5lfY4Q?e=cmunyt

Folgende Dateien wurden umgezogen:

- Liste der Teilnehmenden --> Open Project Vorstand --> Personal (kann nur von berechtigten Personen gesehen werden
- Pressemitteilung und Pressebilder --> General - Hopps --> 07_Pressemitteilungen --> 2024-09-15_Pressemitteilung
- VereinsFin Kickstart Präsentation --> 04_AllgemeineOrga --> 2024-07-17_VereinsFinKickstart

Bitte im Review nochmal prüfen, ob weitere Dokumente fehlen, die noch nicht umgezogen wurden

**Comment by manuelhummler** [comment]
Einwilligungserklärung zur Nutzung von Fotos und Videos für Öffentlichkeitsarbeit --> General - Hopps -> 07_Presse

**Comment by d135-1r43** [comment]
@manuelhummler, das ist jetzt erledigt, oder?

**Comment by manuelhummler** [comment]
@d135-1r43 von meiner Seite aus ja, drum war es in Review. @blackwolfk-9 kümmert sich um die Zugriffe und das Onboarding.
