### ISSUE TITLE
Brand Guideline

### ISSUE THREAD

**Issue by d135-1r43** [hopps-app/hopps#97]
# Story

As a Developer I want to have a brand guideline as PDF. 

# Acceptance

- One page with logo and font definitions (Reddit Sans)
- One page with the colors and their hex for light mode
- One page with the colors and their hex for dark mode

**Comment by lukas-leonhardt** [comment]
Grundsätzlich habe ich den Brand Guideline erstellt. Wenn er final ist, kann ich das als PDF exportieren und an gewünschter Stelle ablegen.
https://www.figma.com/design/1GxaXKEiosDy2PnCZXIMhq/Branding?node-id=381-191&t=aqIJ7HIKNWZ5MdLZ-4

Ich habe noch ein Thema mit den Font Definitions. Ich habe jetzt die Font Styles verwendet, die Rabea in Figma angelegt und in ihrem Design verwendet hat. 

Wollen wir die Text Styles gleich so anlegen, dass sie mit dem Font-System von TailwindCSS zusammenpassen?
https://tailwindcss.com/docs/font-size

Ich finde die Font-Definitionen von TailwindCSS sehr sinnvoll. Dann haben wir in den Frontends auch nicht so viel Konfiguration zu tun + wir haben konsistente Styles über alle Touchpoints (LandingPage, App, WebApp, etc.). 

Wie ist euere Meinung dazu @d135-1r43 @RabeaBonten ?

**Comment by d135-1r43** [comment]
Danke. 

Font Styles sind so fein. Ich würde gern auf Italic verzichten, daher passt es so. Und ja, gern so anlegen, dass es direkt zu der Typografie von Tailwind passt.

**Comment by lukas-leonhardt** [comment]
Ich habe die Typo an die Größen von Tailwind angepasst und eine feste line-height vergeben. Meiner Meinung nach benötigen wir für Body-Texte noch einen leichteren Schriftschnitt (regular). Aber das können wir gerne auch nachziehen, wenn der Bedarf wirklich aufkommt.

PDF ist hier abgelegt: https://openprojectpaf.sharepoint.com/:b:/s/hopps/ERb-0sZr-V5Ai0FMRIjHrdwBDKZtHDGZDGRIupiqByT4tQ?e=HAafUh

**Comment by d135-1r43** [comment]
Danke, das passt so für mich. Bzgl. den Fließtexten: Lass uns einfach mal schauen, wie es ausschaut. Wenn es zu schwer wird, nehmen wir noch einen zweiten Font für die Bodytexte.
